### ISSUE TITLE
[Silent Fail] Running docker-compose up, when other postgres already using port 5432

### ISSUE THREAD

**Issue by dhadrien** [wighawag/jolly-roger#1]
After running

`$ npm run shell:start` 

The docker-compose up tab opened as expected but then was closed on a failure. 

I had already a postgres docker image running 5432:5432. 
The terminal tab just closed with no logs. 

Stoping my postgres image solved the issue.

**Comment by dhadrien** [comment]
By the way, the more I play with it, the more I get excited!

Amazing job!!

**Comment by wighawag** [comment]
Hi @dhadrien thanks for reporting. Not sure yet how I could solve this.
I guess I could at least add some more info in the main console. Will investigate.

Glad you like it :)
