### ISSUE TITLE
how can I access the provider and signer

### ISSUE THREAD

**Issue by railty** [wighawag/jolly-roger#10]
Great work!

Got a question, when you click the button, 
await flow.execute((contracts) => contracts.GreetingsRegistry.setMessage(message));

how can I access the provider, , etc in this function? for example, if I want call
await provider.getBlock(100004), where to get the provider?

Thanks

**Comment by wighawag** [comment]
hi @railty  thanks for the feedback
I should indeed add something
Currently you can access the provider via wallet.provider if I recall

**Comment by wighawag** [comment]
closing as v2 is a complete revamp of v1
