### ISSUE TITLE
Q: Blockscout and interacting with the contract

### ISSUE THREAD

**Issue by nightshift2k** [wighawag/jolly-roger#12]
Hey awesome work, really love it! Just encountered a small drawback, everytime I try to interact with a smart contract via blockexporer that I have deployed and also submitted the code to blockscout I recieve the error when interacting:

Unauthorized

You connected to Unknown Private Network chain in the wallet, but the current instance of Blockscout is for Unknown Private Network chain

did you eventually come across this issue and is there any chance to mitigate this somehow!

Thank you very much in advance!

**Comment by wighawag** [comment]
closing as v2 is a complete revamp of v1
